id: P3377BF42
initial_creation_type: ocr
source_metadata:
  id: bdr:W686
  title: དུས་འཁོར་སྤྱི་དོན་དྲི་མེད་འོད་རྒྱན
  volumes:
    10ac8bdb6b3f4e5387ad66ab13ae2a08:
      image_group_id: I1PD36371
      title: ''
      base_file: v001.txt
  author: ''
